In [1]:
import pandas as pd

In [2]:
data = {
    'user_id': [1, 1, 1, 2, 2, 2],
    'timestamp': ['10:00', '10:01', '10:02', '10:00', '10:01', '10:02'],
    'ping_ms': [20, 22, 21, 30, 32, 150] # User 2 spikes at 10:02
}
df = pd.DataFrame(data)
df

   user_id timestamp  ping_ms
0        1     10:00       20
1        1     10:01       22
2        1     10:02       21
3        2     10:00       30
4        2     10:01       32
5        2     10:02      150

In [3]:
type(df)

pandas.DataFrame

In [4]:
df = df.sort_values(by=['user_id', 'timestamp'])

In [5]:
df

   user_id timestamp  ping_ms
0        1     10:00       20
1        1     10:01       22
2        1     10:02       21
3        2     10:00       30
4        2     10:01       32
5        2     10:02      150

In [6]:
df['ping_spike'] = df.groupby('user_id')['ping_ms'].diff()

In [7]:
# df.drop(columns=['ping_difference'], axis = 0, inplace=True)
# df

In [8]:
df

   user_id timestamp  ping_ms  ping_spike
0        1     10:00       20         NaN
1        1     10:01       22         2.0
2        1     10:02       21        -1.0
3        2     10:00       30         NaN
4        2     10:01       32         2.0
5        2     10:02      150       118.0

In [9]:
anomalies = df[df['ping_spike'] > 50]
anomalies

   user_id timestamp  ping_ms  ping_spike
5        2     10:02      150       118.0